---
- name: Wait for join command file on master
  wait_for:
    path: /tmp/kubeadm_join_cmd.sh
    timeout: 300
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: yes

- name: Fetch kubeadm join command from master
  fetch:
    src: /tmp/kubeadm_join_cmd.sh
    dest: /tmp/kubeadm_join_cmd.sh
    flat: yes
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: yes

- name: Copy join command to worker
  copy:
    src: /tmp/kubeadm_join_cmd.sh
    dest: /tmp/kubeadm_join_cmd.sh
    mode: '0755'

- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Run kubeadm join on worker
  shell: bash /tmp/kubeadm_join_cmd.sh
  when: not kubelet_conf.stat.exists
  become: yes