---
- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_initialized

- name: Initialize Kubernetes Master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: not k8s_initialized.stat.exists
  register: kubeadm_init

- name: Create .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy admin kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Generate kubeadm join command and save to a file
  shell: |
    kubeadm token create --print-join-command > /tmp/kubeadm_join_cmd.sh
  args:
    executable: /bin/bash
  register: join_command    
  when: not k8s_initialized.stat.exists

- name: Make join command executable
  file:
    path: /tmp/kubeadm_join_cmd.sh
    mode: '0755'
