  ---
- hosts: all
  become: yes
  roles:
    - common

- hosts: masters
  become: yes
  roles:
    - kube-master
    - kube-network

- hosts: workers
  become: yes
  roles:
    - kube-worker                                  